---
title: Component beperkingen van de Raspberry Pi Pico
hero_image: images/banner.png
description: Hoeveel componenten kunnen met jumper draden worden gekoppeld aan een Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-22"
steps:
  - title: Component beperkingen van de Raspberry Pi Pico
