title: Limitations of the Raspberry Pi Pico
hero_image: images/banner.png
description: pico-limitations description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-22"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
