title: Component limitations of the Raspberry Pi Pico
hero_image: images/banner.png
description: How many components can be attached with jumper wires to a Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-22"
steps:
  - title: Component limitations of the Raspberry Pi Pico
