title: Limitações de componentes do Raspberry Pi Pico
hero_image: images/banner.png
description: Quantos componentes podem ser conectados atraves de jumpers a um Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-22"
steps:
  - 
    title: Limitações de componentes do Raspberry Pi Pico
