title: Limitaciones de los componentes de Raspberry Pi Pico
hero_image: images/banner.png
description: '¿Cuántos componentes se pueden conectar con cables puente a un Raspberry Pi Pico?'
version: 4
listed: false
copyedit: false
last_tested: "2022-02-22"
steps:
  - 
    title: Limitaciones de los componentes de Raspberry Pi Pico
