title: حدود المكون في Raspberry Pi Pico
hero_image: images/banner.png
description: كم عدد المكونات التي يمكن توصيلها بأسلاك التوصيل إلى Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-22"
steps:
  - 
    title: قيود المكون في Raspberry Pi Pico
