title: Limitations des composants du Raspberry Pi Pico
hero_image: images/banner.png
description: Combien de composants peuvent être connectés avec des fils de liaison à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-22"
steps:
  - 
    title: Limitations des composants du Raspberry Pi Pico
